### ISSUE TITLE
Headers spec is incorrect. Should be "headers" not "header

### ISSUE THREAD

**Issue by zmslb** [kigiri/fetch#4]
The Fetch API uses the key "headers" not "header" in the options object passed as the second argument to the fetch(..) call. (Source: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Supplying_request_options)

The current GitHub.io site uses "header" incorrectly, which will cause requests to be rejected.

On this Github.io site,

`curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer token' 'http://stuff.google.com'`

 the above input yields:

`fetch("http://stuff.google.com", {
  header: {
    Accept: "application/json",
    Authorization: "Bearer token"
  }
})`

which should actually be,

`fetch("http://stuff.google.com", {
    headers: {
    Accept: "application/json",
    Authorization: "Bearer token"
  }
})`

**Comment by zmslb** [comment]
Apologies I hit accidentally hit cmd-enter too quickly.

**Comment by kigiri** [comment]
Thank's it's should work properly

**Comment by zmslb** [comment]
Thank you -- useful little website, hope it can help others.

**Comment by kigiri** [comment]
Yeah I could do a few things to improve it, like removing ignored headers so you know they are not passed.
Also adding use the `credential: 'include'` instead of cookie headers and stuff, but i'm not sure how to do it yet and it's only important for client-side fetch, I sometime use it with `node-fetch` so...

If you see anything keep them PR comming haha
